# Generated by Django 3.0.8 on 2020-07-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='tx_name', max_length=100)),
                ('gender', models.CharField(db_column='cs_gender', max_length=1)),
                ('salary', models.DecimalField(db_column='nb_salary', decimal_places=2, max_digits=10)),
                ('date_birth', models.DateField(db_column='dt_birth')),
            ],
            options={
                'db_table': 'person',
                'managed': True,
            },
        ),
    ]
